server:
  port: 8082
spring:
  application:
    name: hospital # 应用名称
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 2
      publisher-confirms: true
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
logging:
  level:
    com.taimi: debug